environment: test

connectors:
  - file: connectorDemo
    name: exo
    params:
      testType: withdrawal

monitors:
  - file: monitorHijack
    channel: hijack
    name: basic-hijack-detection
    params:
      thresholdMinPeers: 0

  - file: monitorNewPrefix
    channel: newprefix
    name: prefix-detection
    params:
      thresholdMinPeers: 0

  - file: monitorVisibility
    channel: visibility
    name: withdrawal-detection
    params:
      thresholdMinPeers: 0

  - file: monitorPath
    channel: path
    name: path-matching
    params:
      thresholdMinPeers: 0

  - file: monitorAS
    channel: misconfiguration
    name: asn-monitor
    params:
      thresholdMinPeers: 0

  - file: monitorRPKI
    channel: rpki
    name: rpki-monitor
    params:
      thresholdMinPeers: 1
      preCacheROAs: false
      checkUncovered: true


reports:
  - file: reportFile
    channels:
      - hijack
      - newprefix
      - visibility
      - path
      - misconfiguration
      - rpki
    params:
      persistAlertData: false
      alertDataDirectory: alertdata/


# The file containing the monitored prefixes. Please see monitored_prefixes_test.yml for an example
# This is an array (use new lines and dashes!)
monitoredPrefixesFiles:
  - exo-prefixes.demo.yml

logging:
  directory: logs
  logRotatePattern: YYYY-MM-DD # Whenever the pattern changes, a new file is created and the old one rotated
  backlogSize: 1
  maxRetainedFiles: 10
  maxFileSizeMB: 15
  compressOnRotation: true

checkForUpdatesAtBoot: false
persistStatus: false

volume: demovolume/

processMonitors:
  - file: uptimeApi
    params:
      useStatusCodes: true
      host: null
      port: 8011


notificationIntervalSeconds: 120 # Repeat the same alert (which keeps being triggered) after x seconds
alertOnlyOnce: false
fadeOffSeconds: 10
checkFadeOffGroupsSeconds: 2
pidFile: bgpalerter.pid
multiProcess: false
maxMessagesPerSecond: 6000
